language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -r requirements_dev.txt
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Db6Dtran2YaToMT63ETf+dPyj3kUq+O2jvJNBK4GeH0SnEHxUaauCQf5rZAdki1BnuUNarkMVjqKafJi8n6GM5Z2VbO/zwSQycE4LzmYzKCyn6MBWlp3H0mN0LV6vAwC6dWyhkf6PncyBr79ywO4PalLX2ZiG1yafkCbkQpM5OwtSrwfmDAUpBsot+rXPoVpHkreA+sfWX+WGcpoZhFFZQVUrLOfbjwgqVRrGVojmv6jBDMe3G58tHwTecVOpWUWX9yh7ZtQqs1HNpCwKOnvjYHde2hcm01fjXVkNNrO15Q3HX/k4C/wxbjbVcpf9ABYbWIkzi1ViJvFeo5vHKB0Q1E3WW/frQCn5kdS1FwAGUXEH2zgyjJ3bdM3TRVy1Pc1KaQ5Mgi/ARqianuFnBU+kgSu1BX8U6pDP2hGZeSun4UEpwUc4HJyS8mGLyo4kW9QEC9kinVUbMyxAqDg5omf9qsI9LWxVFTamKjbDLG+g2RwCmt+0h6ExCxlh3IKLWHuKOOIcNxbdNPqhfFpC9LPMrMrtXydzW+Y/UwmyuE2ka/4Dd71ZI2pHj+ny15hye8Ex5xutr2xp78NWqJuVGUltAXTv+Tm9bf3l3ZCSelH39svot6VDyvD0fiwUS/1fDFXW/xaQwMjZEhYsr7fqmEeU9KCwsvac2ajx8isrezKRKQ=
  true:
    tags: true
    repo: contagon/ldsnotes
    python: 3.8
env:
  global:
    secure: MZ/sa/L0VfFwtm4TF/+m5ZpVkJedMWzbDWqgrpDRMUdE1YV/WLRlQTSKjVVjJGvjElUInnOiYYJIINzNQrWw+twDJuoBKLSAiPw2euNJW27m3st3grvTLww20/CFSv5DIh0abxwE4UG42oQUFCcqZL2LJ60ycnuO80l3h7XnDTgXq0Ea7lFe2OfOBSD39JPcGynt9Lbkkh/3bsJFURkQNtJ1p3PwJ9XniMG1jQw3PeikepddZG5iSY9Yc6ydEFl7jietmCeWOnlj6v90FJxy+Zj8C11hbpCnG2Nszwh9D8/mjWWfCBVig2uoT3bO1yIjkVFN5t0zYhEXEH7yBwoLe1upRzaF8Vl73SMy3cL9JA/TsSuFiSU2bpJ/5iD1ZzSKbX+l9eXVdLbNHveUwI8JdzSDbGq7sOnUg7ES/hgKvgL3h/z4N3478F+MKw5OntT+KTIuypVbId1iBK8Y0Ge1yREzrG+RiHls6/fx0RqjRDoDr58sOiq1ONaYur/qd4GpTkRoQ/sCpDpgT6SHQ0qJ89aqY4t0oZFvEnJ/2HXiiYfHkS5C9xYW39iuxQnz8ZBYufOUzWnbaBVHibfOJcZoyO68OFSdcK/A+lPWFQ0tq7xvPv87GreyX1HImecn5q5vv8CSn1Xe5gAIZUoJAskWwtshyTWU5ssljM+3NOhqV9E=
