language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -r requirements_dev.txt
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: contagon
  password:
    secure: fCdfxIsQsktMUGIvgDsu8FnqcTMzPYo8yGwfug+IDJoHMTqjJAC2h1aaPycQ/lWqJWQZ05NsGFZBqtR7+/BzgYUEtgEsIQN0N9bytxu9UmLpZ4f0MwudEmPRwlbMIAzFagaY7VLVbn6T0KbV7Wh+Ia2eoVowFLooHkPGVBCUNtJLPkO92b9J9OGq59AFry3Drgk7cby5vhjvOLKw/dRvFsXiih7cBWB0rWQK9ofpVtXORuB96uodxjCA/iR+CFN4MG3W3FaWH14arobucztHXsWlNfUBNKzb7FDkNoTjWeFe9MwwsZUTOZVzIP2IOIQfnSjglaL5NxEJijH2YrE5yQGI0aSRUIwrNgzq6HjUZnBw8sp2A18frB4q2mDvVG//tEETV2dE6zBidWuGjWpIMBMbHFQlMuBPKmoG0gs8gV2+roo7lIEpu0QuI8YeEtm8S3v7VecG7pq/dswNGj+4cl7FPjIZ9dc394lmoYAPylpJakbhID7NbsKTlLVGHN6x52hKn5CVR31UzXxgTWEnyCSJxI6n7KxQWIYYwEiGhEkEwMqfKzBJpZc/1wSeMqTe6tMKX51SC58GfkFJ8g5njpfFnRTqhEr0zLOuclblJNBt5yt6H2DEDNzRavty/nBVWNShF2bl+dhKq52Tb5851vnUK6A/YnKR1/o5IvOyT+k=
  true:
    tags: true
    repo: contagon/ldsnotes
    python: 3.8
