language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -r requirements_dev.txt
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: LHHst/jjyz1BcNYKFtZB+vLdhxg35dGYVkRaR79qR5dZgQUUr9LKQW+WQ8Y+4XdFHHWP84Ogr5rt60skouIyOHlEAdAkDfB9ZKDPeqQaQMpRNrTYXkwIo7HYNk+o2mKclyXvfaI213F0cBVkQ2BNcd3558EvwKsgQi34NrTkXjLdeoxLVsTB8LMDyafuhJ1BrGqzlpXqZP/lObr12XOdypA92ZexaneZZx4MpkVvuwiWiajQkq4ENOFvPeWsvNWsxor3fCNjtBaRxwdJ/9tRavLiAUd+mZDbDlwbizTpSmKdJxI80AVsC7jZ89ar+06KqHSXgAxkOBFs93SyBEi8lHAxMqDZYxhV2g5UR78sEe68/gacAs9hMOKSWf6En5/XfSKjji8avvxeBi2wT3RaeyOXNhljdBBQ1Lk5d3nYsqSHCcHgVcf9lyVb/qOHQ8s6RCBoEsAeR3LoPwzXkPlAM1uy1DU/wsLXKjiLTJupWAAn24RAmMLIW92Vnz4gJaLHUSPSRyhdB/BICk38hZrMmdY6ALPdmFbXHXNkdKEbLlHp3OUekS+VlCY/effEwpMphoFS+Lmu6dyd55PVGo01K6t3X2aWG9aQbPlW5ego/jmWXO3c+vLNjeZBsFPKDVTD/g8A3XrmeWToYMi5tT/va0LN1d6oLq6fBTnu4fJ18UY=
  true:
    tags: true
    repo: contagon/ldsnotes
    python: 3.8
